"""
GitHub API client for issue and PR management.
"""

import os
import logging
from github import Github, Auth
from typing import Optional

log = logging.getLogger("agent")


class GitHubClient:
    """Handles GitHub API interactions."""

    def __init__(self, repo_name: str):
        """
        Initialize GitHub client.

        Args:
            repo_name: Repository in format "owner/repo"
        """
        token = os.environ["GITHUB_TOKEN"]
        self.gh = Github(auth=Auth.Token(token))
        self.repo = self.gh.get_repo(repo_name)
        self.repo_name = repo_name
        # Get default branch from GitHub API (e.g., "main", "dev", "master")
        self.default_branch = self.repo.default_branch
        log.info(f"Repository {repo_name} uses default branch: {self.default_branch}")

    def find_next_issue(self, label: str):
        """
        Find the next open issue with the specified label.
        Returns the OLDEST issue first (lowest number) to process in order.

        Args:
            label: Issue label to filter by

        Returns:
            Issue object or None if no issues found
        """
        for issue in self.repo.get_issues(state="open", labels=[label], sort="created", direction="asc"):
            if not issue.pull_request:
                return issue
        return None

    def get_pr_by_branch(self, branch: str):
        """
        Find a PR by its head branch name.

        Args:
            branch: Branch name to search for

        Returns:
            PR object or None if not found
        """
        for pr in self.repo.get_pulls(state="open", head=branch):
            return pr
        return None

    def create_pull_request(self, branch: str, issue, body_suffix: str = "", summary: str = "", base: str = "main", previous_pr_number: int = None) -> str:
        """
        Create a pull request for the issue.

        Args:
            branch: Branch name to create PR from
            issue: GitHub Issue object
            body_suffix: Optional text to append to PR body
            summary: Summary of changes from Claude Code
            base: Base branch for the PR (default: "main")
            previous_pr_number: If stacking, the PR number this one depends on

        Returns:
            PR URL
        """
        # Build PR body with summary and stats
        body_parts = [f"Automated implementation for #{issue.number}\n"]

        # Add stacking warning if applicable
        if previous_pr_number:
            body_parts.append(
                f"\n**[WARNING] Stacked PR** - This PR is based on #{previous_pr_number}. "
                f"Merge that PR first, then this one will automatically update to target `main`.\n"
            )

        if summary:
            body_parts.append(f"\n{summary}\n")

        if body_suffix:
            body_parts.append(f"\n{body_suffix}")

        body_parts.append("\n---\n*Generated by autonomous agent using Claude Code.*")

        body = "".join(body_parts)

        pr = self.repo.create_pull(
            title=f"Agent: {issue.title}",
            body=body,
            head=branch,
            base=base,
        )
        return pr.html_url

    def close_issue(self, issue, pr_url: str) -> None:
        """
        Close an issue with a comment linking to the PR.

        Args:
            issue: GitHub Issue object
            pr_url: URL of the created PR
        """
        issue.create_comment(
            f"Implementation complete. PR: {pr_url}"
        )
        issue.edit(state="closed")

    def add_issue_comment(self, issue, comment: str) -> None:
        """
        Add a comment to an issue.

        Args:
            issue: GitHub Issue object
            comment: Comment text
        """
        issue.create_comment(comment)
