"""
GitHub API client for issue and PR management.
"""

import os
import logging
from github import Github, Auth
from typing import Optional

log = logging.getLogger("agent")


class GitHubClient:
    """Handles GitHub API interactions."""

    def __init__(self, repo_name: str):
        """
        Initialize GitHub client.

        Args:
            repo_name: Repository in format "owner/repo"
        """
        token = os.environ["GITHUB_TOKEN"]
        self.gh = Github(auth=Auth.Token(token))
        self.repo = self.gh.get_repo(repo_name)
        self.repo_name = repo_name
        # Get default branch from GitHub API (e.g., "main", "dev", "master")
        self.default_branch = self.repo.default_branch
        log.info(f"Repository {repo_name} uses default branch: {self.default_branch}")

    def find_next_issue(self, label: str):
        """
        Find the next open issue with the specified activation label.
        Returns the OLDEST issue first (lowest number) to process in order.
        Skips issues that are already assigned (locked by another agent).

        Args:
            label: Issue label to filter by (activation label like "agent-task")

        Returns:
            Issue object or None if no issues found
        """
        # Search for the oldest issue with the activation label
        for issue in self.repo.get_issues(state="open", labels=[label], sort="created", direction="asc"):
            # Skip pull requests
            if issue.pull_request:
                continue

            # Skip issues that are already assigned (another agent is working on it)
            if issue.assignees:
                log.info(f"Skipping issue #{issue.number} - already assigned to {[a.login for a in issue.assignees]}")
                continue

            return issue

        return None

    def get_pr_by_branch(self, branch: str):
        """
        Find a PR by its head branch name.

        Args:
            branch: Branch name to search for

        Returns:
            PR object or None if not found
        """
        # GitHub API requires owner:branch format
        # Get owner from repo name (e.g., "aignermax/Connect-A-PIC-Pro" -> "aignermax")
        owner = self.repo_name.split('/')[0]
        head_ref = f"{owner}:{branch}"

        try:
            for pr in self.repo.get_pulls(state="open", head=head_ref):
                return pr
        except Exception:
            # Fallback: search manually through all open PRs
            for pr in self.repo.get_pulls(state="open"):
                if pr.head.ref == branch:
                    return pr

        return None

    def create_pull_request(self, branch: str, issue, body_suffix: str = "", summary: str = "", base: str = "main", previous_pr_number: int = None) -> str:
        """
        Create a pull request for the issue.

        Args:
            branch: Branch name to create PR from
            issue: GitHub Issue object
            body_suffix: Optional text to append to PR body
            summary: Summary of changes from Claude Code
            base: Base branch for the PR (default: "main")
            previous_pr_number: If stacking, the PR number this one depends on

        Returns:
            PR URL
        """
        # Build PR body with summary and stats
        body_parts = [f"Automated implementation for #{issue.number}\n"]

        # Add stacking warning if applicable
        if previous_pr_number:
            body_parts.append(
                f"\n**[WARNING] Stacked PR** - This PR is based on #{previous_pr_number}. "
                f"Merge that PR first, then this one will automatically update to target `main`.\n"
            )

        if summary:
            body_parts.append(f"\n{summary}\n")

        if body_suffix:
            body_parts.append(f"\n{body_suffix}")

        body_parts.append("\n---\n*Generated by autonomous agent using Claude Code.*")

        body = "".join(body_parts)

        pr = self.repo.create_pull(
            title=f"Agent: {issue.title}",
            body=body,
            head=branch,
            base=base,
        )
        return pr.html_url

    def close_issue(self, issue, pr_url: str) -> None:
        """
        Close an issue with a comment linking to the PR.
        Also removes assignment to release the lock.

        Args:
            issue: GitHub Issue object
            pr_url: URL of the created PR
        """
        issue.create_comment(
            f"Implementation complete. PR: {pr_url}"
        )

        # Remove assignment to release lock
        try:
            if issue.assignees:
                issue.remove_from_assignees(*issue.assignees)
                log.info(f"Removed assignment from issue #{issue.number} (lock released)")
        except Exception as e:
            log.warning(f"Could not remove assignment: {e}")

        issue.edit(state="closed")

    def add_issue_comment(self, issue, comment: str) -> None:
        """
        Add a comment to an issue.

        Args:
            issue: GitHub Issue object
            comment: Comment text
        """
        issue.create_comment(comment)

    def find_qa_failed_prs(
        self, label: str = "qa-failed", title_prefix: str = "Agent:"
    ) -> list:
        """Return open coder-style PRs currently flagged as qa-failed.

        Filtered by `title_prefix` so we don't try to fix PRs the agent
        didn't author. Sorted oldest-first to match the rest of the
        scheduling policy.
        """
        wanted_label = label.lower()
        result = []
        for pr in self.repo.get_pulls(state="open", sort="created", direction="asc"):
            if not pr.title.startswith(title_prefix):
                continue
            labels = {(getattr(l, "name", "") or "").lower() for l in (pr.labels or [])}
            if wanted_label in labels:
                result.append(pr)
        return result

    def get_latest_qa_comment(self, pr) -> Optional[str]:
        """Return the most recent `[qa-agent]` verdict comment body, if any."""
        latest = None
        try:
            for c in pr.get_issue_comments():
                body = c.body or ""
                if body.startswith("[qa-agent]"):
                    latest = body
        except Exception as e:
            log.warning(f"Could not read comments on PR #{pr.number}: {e}")
        return latest

    def count_qa_failures(self, pr) -> int:
        """Count how many times QA has marked this PR FAILED."""
        n = 0
        try:
            for c in pr.get_issue_comments():
                if (c.body or "").startswith("[qa-agent] **FAILED**"):
                    n += 1
        except Exception as e:
            log.warning(f"Could not count QA failures on PR #{pr.number}: {e}")
        return n

    def remove_pr_label(self, pr, label: str) -> None:
        """Remove a label from a PR, swallowing 'not found' errors."""
        try:
            pr.remove_from_labels(label)
        except Exception as e:
            log.warning(f"Could not remove '{label}' from PR #{pr.number}: {e}")
