"""
GitHub API client for issue and PR management.
"""

import os
import logging
from github import Github, Auth
from typing import Optional

log = logging.getLogger("agent")


class GitHubClient:
    """Handles GitHub API interactions."""

    def __init__(self, repo_name: str):
        """
        Initialize GitHub client.

        Args:
            repo_name: Repository in format "owner/repo"
        """
        token = os.environ["GITHUB_TOKEN"]
        self.gh = Github(auth=Auth.Token(token))
        self.repo = self.gh.get_repo(repo_name)
        self.repo_name = repo_name

    def find_next_issue(self, label: str):
        """
        Find the next open issue with the specified label.

        Args:
            label: Issue label to filter by

        Returns:
            Issue object or None if no issues found
        """
        for issue in self.repo.get_issues(state="open", labels=[label]):
            if not issue.pull_request:
                return issue
        return None

    def create_pull_request(self, branch: str, issue, body_suffix: str = "") -> str:
        """
        Create a pull request for the issue.

        Args:
            branch: Branch name to create PR from
            issue: GitHub Issue object
            body_suffix: Optional text to append to PR body

        Returns:
            PR URL
        """
        body = (
            f"Automated implementation for #{issue.number}\n\n"
            f"{body_suffix}\n"
            f"---\n"
            f"*Generated by autonomous agent using Claude Code.*"
        )

        pr = self.repo.create_pull(
            title=f"Agent: {issue.title}",
            body=body,
            head=branch,
            base="main",
        )
        return pr.html_url

    def close_issue(self, issue, pr_url: str) -> None:
        """
        Close an issue with a comment linking to the PR.

        Args:
            issue: GitHub Issue object
            pr_url: URL of the created PR
        """
        issue.create_comment(
            f"Implementation complete. PR: {pr_url}"
        )
        issue.edit(state="closed")

    def add_issue_comment(self, issue, comment: str) -> None:
        """
        Add a comment to an issue.

        Args:
            issue: GitHub Issue object
            comment: Comment text
        """
        issue.create_comment(comment)
